package ModelsAditivos;

import java.util.HashSet;
import java.util.Set;

public class PaisesValidos {
    private static final Set<String> paisesValidos = new HashSet<>();

    static {
        paisesValidos.add("Afganistán");
        paisesValidos.add("Albania");
        paisesValidos.add("Alemania");
        paisesValidos.add("Andorra");
        paisesValidos.add("Angola");
        paisesValidos.add("Antigua y Barbuda");
        paisesValidos.add("Arabia Saudita");
        paisesValidos.add("Argelia");
        paisesValidos.add("Argentina");
        paisesValidos.add("Armenia");
        paisesValidos.add("Australia");
        paisesValidos.add("Austria");
        paisesValidos.add("Azerbaiyán");
        paisesValidos.add("Bahamas");
        paisesValidos.add("Bangladés");
        paisesValidos.add("Barbados");
        paisesValidos.add("Baréin");
        paisesValidos.add("Bélgica");
        paisesValidos.add("Belice");
        paisesValidos.add("Benín");
        paisesValidos.add("Bielorrusia");
        paisesValidos.add("Birmania");
        paisesValidos.add("Bolivia");
        paisesValidos.add("Bosnia y Herzegovina");
        paisesValidos.add("Botsuana");
        paisesValidos.add("Brasil");
        paisesValidos.add("Brunéi");
        paisesValidos.add("Bulgaria");
        paisesValidos.add("Burkina Faso");
        paisesValidos.add("Burundi");
        paisesValidos.add("Bután");
        paisesValidos.add("Cabo Verde");
        paisesValidos.add("Camboya");
        paisesValidos.add("Camerún");
        paisesValidos.add("Canadá");
        paisesValidos.add("Catar");
        paisesValidos.add("Chad");
        paisesValidos.add("Chile");
        paisesValidos.add("China");
        paisesValidos.add("Chipre");
        paisesValidos.add("Ciudad del Vaticano");
        paisesValidos.add("Colombia");
        paisesValidos.add("Comoras");
        paisesValidos.add("Corea del Norte");
        paisesValidos.add("Corea del Sur");
        paisesValidos.add("Costa de Marfil");
        paisesValidos.add("Costa Rica");
        paisesValidos.add("Croacia");
        paisesValidos.add("Cuba");
        paisesValidos.add("Dinamarca");
        paisesValidos.add("Dominica");
        paisesValidos.add("Ecuador");
        paisesValidos.add("Egipto");
        paisesValidos.add("El Salvador");
        paisesValidos.add("Emiratos Árabes Unidos");
        paisesValidos.add("Eritrea");
        paisesValidos.add("Eslovaquia");
        paisesValidos.add("Eslovenia");
        paisesValidos.add("España");
        paisesValidos.add("Estados Unidos");
        paisesValidos.add("Estonia");
        paisesValidos.add("Etiopía");
        paisesValidos.add("Filipinas");
        paisesValidos.add("Finlandia");
        paisesValidos.add("Fiyi");
        paisesValidos.add("Francia");
        paisesValidos.add("Gabón");
        paisesValidos.add("Gambia");
        paisesValidos.add("Georgia");
        paisesValidos.add("Ghana");
        paisesValidos.add("Granada");
        paisesValidos.add("Grecia");
        paisesValidos.add("Guatemala");
        paisesValidos.add("Guyana");
        paisesValidos.add("Guinea");
        paisesValidos.add("Guinea-Bisáu");
        paisesValidos.add("Guinea Ecuatorial");
        paisesValidos.add("Haití");
        paisesValidos.add("Honduras");
        paisesValidos.add("Hungría");
        paisesValidos.add("India");
        paisesValidos.add("Indonesia");
        paisesValidos.add("Irak");
        paisesValidos.add("Irán");
        paisesValidos.add("Irlanda");
        paisesValidos.add("Islandia");
        paisesValidos.add("Islas Marshall");
        paisesValidos.add("Islas Salomón");
        paisesValidos.add("Israel");
        paisesValidos.add("Italia");
        paisesValidos.add("Jamaica");
        paisesValidos.add("Japón");
        paisesValidos.add("Jordania");
        paisesValidos.add("Kazajistán");
        paisesValidos.add("Kenia");
        paisesValidos.add("Kirguistán");
        paisesValidos.add("Kiribati");
        paisesValidos.add("Kuwait");
        paisesValidos.add("Laos");
        paisesValidos.add("Lesoto");
        paisesValidos.add("Letonia");
        paisesValidos.add("Líbano");
        paisesValidos.add("Liberia");
        paisesValidos.add("Libia");
        paisesValidos.add("Liechtenstein");
        paisesValidos.add("Lituania");
        paisesValidos.add("Luxemburgo");
        paisesValidos.add("Macedonia del Norte");
        paisesValidos.add("Madagascar");
        paisesValidos.add("Malasia");
        paisesValidos.add("Malaui");
        paisesValidos.add("Maldivas");
        paisesValidos.add("Malí");
        paisesValidos.add("Malta");
        paisesValidos.add("Marruecos");
        paisesValidos.add("Mauricio");
        paisesValidos.add("Mauritania");
        paisesValidos.add("México");
        paisesValidos.add("Micronesia");
        paisesValidos.add("Moldavia");
        paisesValidos.add("Mónaco");
        paisesValidos.add("Mongolia");
        paisesValidos.add("Montenegro");
        paisesValidos.add("Mozambique");
        paisesValidos.add("Namibia");
        paisesValidos.add("Nauru");
        paisesValidos.add("Nepal");
        paisesValidos.add("Nicaragua");
        paisesValidos.add("Níger");
        paisesValidos.add("Nigeria");
        paisesValidos.add("Noruega");
        paisesValidos.add("Nueva Zelanda");
        paisesValidos.add("Omán");
        paisesValidos.add("Países Bajos");
        paisesValidos.add("Pakistán");
        paisesValidos.add("Palaos");
        paisesValidos.add("Panamá");
        paisesValidos.add("Papúa Nueva Guinea");
        paisesValidos.add("Paraguay");
        paisesValidos.add("Perú");
        paisesValidos.add("Polonia");
        paisesValidos.add("Portugal");
        paisesValidos.add("Reino Unido");
        paisesValidos.add("República Centroafricana");
        paisesValidos.add("República Checa");
        paisesValidos.add("República del Congo");
        paisesValidos.add("República Democrática del Congo");
        paisesValidos.add("República Dominicana");
        paisesValidos.add("Ruanda");
        paisesValidos.add("Rumania");
        paisesValidos.add("Rusia");
        paisesValidos.add("Samoa");
        paisesValidos.add("San Cristóbal y Nieves");
        paisesValidos.add("San Marino");
        paisesValidos.add("San Vicente y las Granadinas");
        paisesValidos.add("Santa Lucía");
        paisesValidos.add("Santo Tomé y Príncipe");
        paisesValidos.add("Senegal");
        paisesValidos.add("Serbia");
        paisesValidos.add("Seychelles");
        paisesValidos.add("Sierra Leona");
        paisesValidos.add("Singapur");
        paisesValidos.add("Siria");
        paisesValidos.add("Somalia");
        paisesValidos.add("Sri Lanka");
        paisesValidos.add("Suazilandia");
        paisesValidos.add("Sudáfrica");
        paisesValidos.add("Sudán");
        paisesValidos.add("Sudán del Sur");
        paisesValidos.add("Suecia");
        paisesValidos.add("Suiza");
        paisesValidos.add("Surinam");
        paisesValidos.add("Tailandia");
        paisesValidos.add("Tanzania");
        paisesValidos.add("Tayikistán");
        paisesValidos.add("Timor Oriental");
        paisesValidos.add("Togo");
        paisesValidos.add("Tonga");
        paisesValidos.add("Trinidad y Tobago");
        paisesValidos.add("Túnez");
        paisesValidos.add("Turkmenistán");
        paisesValidos.add("Turquía");
        paisesValidos.add("Tuvalu");
        paisesValidos.add("Ucrania");
        paisesValidos.add("Uganda");
        paisesValidos.add("Uruguay");
        paisesValidos.add("Uzbekistán");
        paisesValidos.add("Vanuatu");
        paisesValidos.add("Venezuela");
        paisesValidos.add("Vietnam");
        paisesValidos.add("Yemen");
        paisesValidos.add("Yibuti");
        paisesValidos.add("Zambia");
        paisesValidos.add("Zimbabue");
    }

    public static boolean esPaisValido(String pais) {
        return paisesValidos.contains(pais);
    }
}